//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.30 at 12:18:26 PM EDT 
//


package com.rsa.transarmor.dto;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for BillPayGrp complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BillPayGrp">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{com/firstdata/Merchant/gmfV3.10}BillPymtTxnInd" minOccurs="0"/>
 *         &lt;element ref="{com/firstdata/Merchant/gmfV3.10}MerchAdviceCode" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BillPayGrp", propOrder = {
    "billPymtTxnInd",
    "merchAdviceCode"
})
public class BillPayGrp {

    @XmlElement(name = "BillPymtTxnInd")
    protected BillPymtTxnIndType billPymtTxnInd;
    @XmlElement(name = "MerchAdviceCode")
    protected String merchAdviceCode;

    /**
     * Gets the value of the billPymtTxnInd property.
     * 
     * @return
     *     possible object is
     *     {@link BillPymtTxnIndType }
     *     
     */
    public BillPymtTxnIndType getBillPymtTxnInd() {
        return billPymtTxnInd;
    }

    /**
     * Sets the value of the billPymtTxnInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link BillPymtTxnIndType }
     *     
     */
    public void setBillPymtTxnInd(BillPymtTxnIndType value) {
        this.billPymtTxnInd = value;
    }

    /**
     * Gets the value of the merchAdviceCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMerchAdviceCode() {
        return merchAdviceCode;
    }

    /**
     * Sets the value of the merchAdviceCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMerchAdviceCode(String value) {
        this.merchAdviceCode = value;
    }

}
