//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.30 at 12:18:26 PM EDT 
//


package com.rsa.transarmor.dto;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CardTagType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="CardTagType">
 *   &lt;restriction base="{com/firstdata/Merchant/gmfV3.10}Max3AN">
 *     &lt;enumeration value="CC"/>
 *     &lt;enumeration value="TE"/>
 *     &lt;enumeration value="DS"/>
 *     &lt;enumeration value="AO"/>
 *     &lt;enumeration value="DB"/>
 *     &lt;enumeration value="FL"/>
 *     &lt;enumeration value="CS"/>
 *     &lt;enumeration value="PR"/>
 *     &lt;enumeration value="CK"/>
 *     &lt;enumeration value="EF"/>
 *     &lt;enumeration value="EC"/>
 *     &lt;enumeration value="SV1"/>
 *     &lt;enumeration value="SV2"/>
 *     &lt;enumeration value="SV3"/>
 *     &lt;enumeration value="SV4"/>
 *     &lt;enumeration value="ECA"/>
 *     &lt;enumeration value="WIC"/>
 *     &lt;enumeration value="EK"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "CardTagType")
@XmlEnum
public enum CardTagType {

    CC("CC"),
    TE("TE"),
    DS("DS"),
    AO("AO"),
    DB("DB"),
    FL("FL"),
    CS("CS"),
    PR("PR"),
    CK("CK"),
    EF("EF"),
    EC("EC"),
    @XmlEnumValue("SV1")
    SV_1("SV1"),
    @XmlEnumValue("SV2")
    SV_2("SV2"),
    @XmlEnumValue("SV3")
    SV_3("SV3"),
    @XmlEnumValue("SV4")
    SV_4("SV4"),
    ECA("ECA"),
    WIC("WIC"),
    EK("EK");
    private final String value;

    CardTagType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static CardTagType fromValue(String v) {
        for (CardTagType c: CardTagType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
