//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.30 at 12:18:26 PM EDT 
//


package com.rsa.transarmor.dto;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CardTypeType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="CardTypeType">
 *   &lt;restriction base="{com/firstdata/Merchant/gmfV3.10}Max10AN">
 *     &lt;enumeration value="Amex"/>
 *     &lt;enumeration value="Diners"/>
 *     &lt;enumeration value="Discover"/>
 *     &lt;enumeration value="JCB"/>
 *     &lt;enumeration value="MasterCard"/>
 *     &lt;enumeration value="Visa"/>
 *     &lt;enumeration value="PPayCL"/>
 *     &lt;enumeration value="GiftCard"/>
 *     &lt;enumeration value="Exxon"/>
 *     &lt;enumeration value="CarCareOne"/>
 *     &lt;enumeration value="Shell"/>
 *     &lt;enumeration value="ValeroUCC"/>
 *     &lt;enumeration value="GenProp"/>
 *     &lt;enumeration value="Gulf"/>
 *     &lt;enumeration value="Sinclair"/>
 *     &lt;enumeration value="Sunoco"/>
 *     &lt;enumeration value="Buypass"/>
 *     &lt;enumeration value="Wex"/>
 *     &lt;enumeration value="Voyager"/>
 *     &lt;enumeration value="ValeroFlt"/>
 *     &lt;enumeration value="FleetOne"/>
 *     &lt;enumeration value="MCFleet"/>
 *     &lt;enumeration value="VisaFleet"/>
 *     &lt;enumeration value="FleetCor"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "CardTypeType")
@XmlEnum
public enum CardTypeType {

    @XmlEnumValue("Amex")
    AMEX("Amex"),
    @XmlEnumValue("Diners")
    DINERS("Diners"),
    @XmlEnumValue("Discover")
    DISCOVER("Discover"),
    JCB("JCB"),
    @XmlEnumValue("MasterCard")
    MASTER_CARD("MasterCard"),
    @XmlEnumValue("Visa")
    VISA("Visa"),
    @XmlEnumValue("PPayCL")
    P_PAY_CL("PPayCL"),
    @XmlEnumValue("GiftCard")
    GIFT_CARD("GiftCard"),
    @XmlEnumValue("Exxon")
    EXXON("Exxon"),
    @XmlEnumValue("CarCareOne")
    CAR_CARE_ONE("CarCareOne"),
    @XmlEnumValue("Shell")
    SHELL("Shell"),
    @XmlEnumValue("ValeroUCC")
    VALERO_UCC("ValeroUCC"),
    @XmlEnumValue("GenProp")
    GEN_PROP("GenProp"),
    @XmlEnumValue("Gulf")
    GULF("Gulf"),
    @XmlEnumValue("Sinclair")
    SINCLAIR("Sinclair"),
    @XmlEnumValue("Sunoco")
    SUNOCO("Sunoco"),
    @XmlEnumValue("Buypass")
    BUYPASS("Buypass"),
    @XmlEnumValue("Wex")
    WEX("Wex"),
    @XmlEnumValue("Voyager")
    VOYAGER("Voyager"),
    @XmlEnumValue("ValeroFlt")
    VALERO_FLT("ValeroFlt"),
    @XmlEnumValue("FleetOne")
    FLEET_ONE("FleetOne"),
    @XmlEnumValue("MCFleet")
    MC_FLEET("MCFleet"),
    @XmlEnumValue("VisaFleet")
    VISA_FLEET("VisaFleet"),
    @XmlEnumValue("FleetCor")
    FLEET_COR("FleetCor");
    private final String value;

    CardTypeType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static CardTypeType fromValue(String v) {
        for (CardTypeType c: CardTypeType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
