//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.30 at 12:18:26 PM EDT 
//


package com.rsa.transarmor.dto;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for EcommGrp complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EcommGrp">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{com/firstdata/Merchant/gmfV3.10}EcommTxnInd" minOccurs="0"/>
 *         &lt;element ref="{com/firstdata/Merchant/gmfV3.10}CustSvcPhoneNumber" minOccurs="0"/>
 *         &lt;element ref="{com/firstdata/Merchant/gmfV3.10}EcommURL" minOccurs="0"/>
 *         &lt;element ref="{com/firstdata/Merchant/gmfV3.10}MCSN" minOccurs="0"/>
 *         &lt;element ref="{com/firstdata/Merchant/gmfV3.10}MCSC" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EcommGrp", propOrder = {
    "ecommTxnInd",
    "custSvcPhoneNumber",
    "ecommURL",
    "mcsn",
    "mcsc"
})
public class EcommGrp {

    @XmlElement(name = "EcommTxnInd")
    protected String ecommTxnInd;
    @XmlElement(name = "CustSvcPhoneNumber")
    protected String custSvcPhoneNumber;
    @XmlElement(name = "EcommURL")
    protected String ecommURL;
    @XmlElement(name = "MCSN")
    protected Integer mcsn;
    @XmlElement(name = "MCSC")
    protected Integer mcsc;

    /**
     * Gets the value of the ecommTxnInd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEcommTxnInd() {
        return ecommTxnInd;
    }

    /**
     * Sets the value of the ecommTxnInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEcommTxnInd(String value) {
        this.ecommTxnInd = value;
    }

    /**
     * Gets the value of the custSvcPhoneNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustSvcPhoneNumber() {
        return custSvcPhoneNumber;
    }

    /**
     * Sets the value of the custSvcPhoneNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustSvcPhoneNumber(String value) {
        this.custSvcPhoneNumber = value;
    }

    /**
     * Gets the value of the ecommURL property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEcommURL() {
        return ecommURL;
    }

    /**
     * Sets the value of the ecommURL property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEcommURL(String value) {
        this.ecommURL = value;
    }

    /**
     * Gets the value of the mcsn property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getMCSN() {
        return mcsn;
    }

    /**
     * Sets the value of the mcsn property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setMCSN(Integer value) {
        this.mcsn = value;
    }

    /**
     * Gets the value of the mcsc property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getMCSC() {
        return mcsc;
    }

    /**
     * Sets the value of the mcsc property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setMCSC(Integer value) {
        this.mcsc = value;
    }

}
