//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.30 at 12:18:26 PM EDT 
//


package com.rsa.transarmor.dto;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for FileTypeType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="FileTypeType">
 *   &lt;restriction base="{com/firstdata/Merchant/gmfV3.10}Max10AN">
 *     &lt;enumeration value="EMV2KEY"/>
 *     &lt;enumeration value="MAIL"/>
 *     &lt;enumeration value="CARDTABLE"/>
 *     &lt;enumeration value="DYNCRDTBL"/>
 *     &lt;enumeration value="SITECFG"/>
 *     &lt;enumeration value="HOSTDISC"/>
 *     &lt;enumeration value="RECTXT"/>
 *     &lt;enumeration value="TABLE"/>
 *     &lt;enumeration value="DATETIME"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "FileTypeType")
@XmlEnum
public enum FileTypeType {

    @XmlEnumValue("EMV2KEY")
    EMV_2_KEY("EMV2KEY"),
    MAIL("MAIL"),
    CARDTABLE("CARDTABLE"),
    DYNCRDTBL("DYNCRDTBL"),
    SITECFG("SITECFG"),
    HOSTDISC("HOSTDISC"),
    RECTXT("RECTXT"),
    TABLE("TABLE"),
    DATETIME("DATETIME");
    private final String value;

    FileTypeType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static FileTypeType fromValue(String v) {
        for (FileTypeType c: FileTypeType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
