//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.30 at 12:18:26 PM EDT 
//


package com.rsa.transarmor.dto;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for HostTotGrp complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="HostTotGrp">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{com/firstdata/Merchant/gmfV3.10}TotReqDate" minOccurs="0"/>
 *         &lt;element ref="{com/firstdata/Merchant/gmfV3.10}Password" minOccurs="0"/>
 *         &lt;element ref="{com/firstdata/Merchant/gmfV3.10}NetSettleAmt" minOccurs="0"/>
 *         &lt;element ref="{com/firstdata/Merchant/gmfV3.10}FeeAmt" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "HostTotGrp", propOrder = {
    "totReqDate",
    "password",
    "netSettleAmt",
    "feeAmt"
})
public class HostTotGrp {

    @XmlElement(name = "TotReqDate")
    protected String totReqDate;
    @XmlElement(name = "Password")
    protected String password;
    @XmlElement(name = "NetSettleAmt")
    protected String netSettleAmt;
    @XmlElement(name = "FeeAmt")
    protected String feeAmt;

    /**
     * Gets the value of the totReqDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTotReqDate() {
        return totReqDate;
    }

    /**
     * Sets the value of the totReqDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTotReqDate(String value) {
        this.totReqDate = value;
    }

    /**
     * Gets the value of the password property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPassword() {
        return password;
    }

    /**
     * Sets the value of the password property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPassword(String value) {
        this.password = value;
    }

    /**
     * Gets the value of the netSettleAmt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNetSettleAmt() {
        return netSettleAmt;
    }

    /**
     * Sets the value of the netSettleAmt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNetSettleAmt(String value) {
        this.netSettleAmt = value;
    }

    /**
     * Gets the value of the feeAmt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFeeAmt() {
        return feeAmt;
    }

    /**
     * Sets the value of the feeAmt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFeeAmt(String value) {
        this.feeAmt = value;
    }

}
