//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.30 at 12:18:26 PM EDT 
//


package com.rsa.transarmor.dto;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for MCMSDIType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="MCMSDIType">
 *   &lt;restriction base="{com/firstdata/Merchant/gmfV3.10}Max15AN">
 *     &lt;enumeration value="BillPayment"/>
 *     &lt;enumeration value="Healthcare"/>
 *     &lt;enumeration value="Transit"/>
 *     &lt;enumeration value="EcomAgg"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "MCMSDIType")
@XmlEnum
public enum MCMSDIType {

    @XmlEnumValue("BillPayment")
    BILL_PAYMENT("BillPayment"),
    @XmlEnumValue("Healthcare")
    HEALTHCARE("Healthcare"),
    @XmlEnumValue("Transit")
    TRANSIT("Transit"),
    @XmlEnumValue("EcomAgg")
    ECOM_AGG("EcomAgg");
    private final String value;

    MCMSDIType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static MCMSDIType fromValue(String v) {
        for (MCMSDIType c: MCMSDIType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
