//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.30 at 12:18:26 PM EDT 
//


package com.rsa.transarmor.dto;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for OrigAuthGrp complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="OrigAuthGrp">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{com/firstdata/Merchant/gmfV3.10}OrigAuthID" minOccurs="0"/>
 *         &lt;element ref="{com/firstdata/Merchant/gmfV3.10}OrigLocalDateTime" minOccurs="0"/>
 *         &lt;element ref="{com/firstdata/Merchant/gmfV3.10}OrigTranDateTime" minOccurs="0"/>
 *         &lt;element ref="{com/firstdata/Merchant/gmfV3.10}OrigSTAN" minOccurs="0"/>
 *         &lt;element ref="{com/firstdata/Merchant/gmfV3.10}OrigRespCode" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OrigAuthGrp", propOrder = {
    "origAuthID",
    "origLocalDateTime",
    "origTranDateTime",
    "origSTAN",
    "origRespCode"
})
public class OrigAuthGrp {

    @XmlElement(name = "OrigAuthID")
    protected String origAuthID;
    @XmlElement(name = "OrigLocalDateTime")
    protected String origLocalDateTime;
    @XmlElement(name = "OrigTranDateTime")
    protected String origTranDateTime;
    @XmlElement(name = "OrigSTAN")
    protected String origSTAN;
    @XmlElement(name = "OrigRespCode")
    protected String origRespCode;

    /**
     * Gets the value of the origAuthID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrigAuthID() {
        return origAuthID;
    }

    /**
     * Sets the value of the origAuthID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrigAuthID(String value) {
        this.origAuthID = value;
    }

    /**
     * Gets the value of the origLocalDateTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrigLocalDateTime() {
        return origLocalDateTime;
    }

    /**
     * Sets the value of the origLocalDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrigLocalDateTime(String value) {
        this.origLocalDateTime = value;
    }

    /**
     * Gets the value of the origTranDateTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrigTranDateTime() {
        return origTranDateTime;
    }

    /**
     * Sets the value of the origTranDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrigTranDateTime(String value) {
        this.origTranDateTime = value;
    }

    /**
     * Gets the value of the origSTAN property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrigSTAN() {
        return origSTAN;
    }

    /**
     * Sets the value of the origSTAN property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrigSTAN(String value) {
        this.origSTAN = value;
    }

    /**
     * Gets the value of the origRespCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrigRespCode() {
        return origRespCode;
    }

    /**
     * Sets the value of the origRespCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrigRespCode(String value) {
        this.origRespCode = value;
    }

}
