//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.30 at 12:18:26 PM EDT 
//


package com.rsa.transarmor.dto;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ProdCodeDetGrp complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ProdCodeDetGrp">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{com/firstdata/Merchant/gmfV3.10}NACSProdCode" minOccurs="0"/>
 *         &lt;element ref="{com/firstdata/Merchant/gmfV3.10}UnitOfMsure" minOccurs="0"/>
 *         &lt;element ref="{com/firstdata/Merchant/gmfV3.10}Qnty" minOccurs="0"/>
 *         &lt;element ref="{com/firstdata/Merchant/gmfV3.10}UnitPrice" minOccurs="0"/>
 *         &lt;element ref="{com/firstdata/Merchant/gmfV3.10}ProdAmt" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ProdCodeDetGrp", propOrder = {
    "nacsProdCode",
    "unitOfMsure",
    "qnty",
    "unitPrice",
    "prodAmt"
})
public class ProdCodeDetGrp {

    @XmlElement(name = "NACSProdCode")
    protected String nacsProdCode;
    @XmlElement(name = "UnitOfMsure")
    protected String unitOfMsure;
    @XmlElement(name = "Qnty")
    protected Integer qnty;
    @XmlElement(name = "UnitPrice")
    protected Integer unitPrice;
    @XmlElement(name = "ProdAmt")
    protected String prodAmt;

    /**
     * Gets the value of the nacsProdCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNACSProdCode() {
        return nacsProdCode;
    }

    /**
     * Sets the value of the nacsProdCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNACSProdCode(String value) {
        this.nacsProdCode = value;
    }

    /**
     * Gets the value of the unitOfMsure property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUnitOfMsure() {
        return unitOfMsure;
    }

    /**
     * Sets the value of the unitOfMsure property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUnitOfMsure(String value) {
        this.unitOfMsure = value;
    }

    /**
     * Gets the value of the qnty property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getQnty() {
        return qnty;
    }

    /**
     * Sets the value of the qnty property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setQnty(Integer value) {
        this.qnty = value;
    }

    /**
     * Gets the value of the unitPrice property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getUnitPrice() {
        return unitPrice;
    }

    /**
     * Sets the value of the unitPrice property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setUnitPrice(Integer value) {
        this.unitPrice = value;
    }

    /**
     * Gets the value of the prodAmt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProdAmt() {
        return prodAmt;
    }

    /**
     * Sets the value of the prodAmt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProdAmt(String value) {
        this.prodAmt = value;
    }

}
