//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.30 at 12:18:26 PM EDT 
//


package com.rsa.transarmor.dto;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ProgramIDType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ProgramIDType">
 *   &lt;restriction base="{com/firstdata/Merchant/gmfV3.10}Max20AN">
 *     &lt;enumeration value="InComm"/>
 *     &lt;enumeration value="StoredValueSystems"/>
 *     &lt;enumeration value="Solspark"/>
 *     &lt;enumeration value="Blackhawk"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "ProgramIDType")
@XmlEnum
public enum ProgramIDType {

    @XmlEnumValue("InComm")
    IN_COMM("InComm"),
    @XmlEnumValue("StoredValueSystems")
    STORED_VALUE_SYSTEMS("StoredValueSystems"),
    @XmlEnumValue("Solspark")
    SOLSPARK("Solspark"),
    @XmlEnumValue("Blackhawk")
    BLACKHAWK("Blackhawk");
    private final String value;

    ProgramIDType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ProgramIDType fromValue(String v) {
        for (ProgramIDType c: ProgramIDType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
