//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.30 at 12:18:26 PM EDT 
//


package com.rsa.transarmor.dto;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PymtTypeType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="PymtTypeType">
 *   &lt;restriction base="{com/firstdata/Merchant/gmfV3.10}Max7AN">
 *     &lt;enumeration value="Credit"/>
 *     &lt;enumeration value="Debit"/>
 *     &lt;enumeration value="PLDebit"/>
 *     &lt;enumeration value="EBT"/>
 *     &lt;enumeration value="Check"/>
 *     &lt;enumeration value="Prepaid"/>
 *     &lt;enumeration value="PvtLabl"/>
 *     &lt;enumeration value="Fleet"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "PymtTypeType")
@XmlEnum
public enum PymtTypeType {

    @XmlEnumValue("Credit")
    CREDIT("Credit"),
    @XmlEnumValue("Debit")
    DEBIT("Debit"),
    @XmlEnumValue("PLDebit")
    PL_DEBIT("PLDebit"),
    EBT("EBT"),
    @XmlEnumValue("Check")
    CHECK("Check"),
    @XmlEnumValue("Prepaid")
    PREPAID("Prepaid"),
    @XmlEnumValue("PvtLabl")
    PVT_LABL("PvtLabl"),
    @XmlEnumValue("Fleet")
    FLEET("Fleet");
    private final String value;

    PymtTypeType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static PymtTypeType fromValue(String v) {
        for (PymtTypeType c: PymtTypeType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
