//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.30 at 12:18:26 PM EDT 
//


package com.rsa.transarmor.dto;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SecrTxnGrp complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SecrTxnGrp">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{com/firstdata/Merchant/gmfV3.10}VisaXID" minOccurs="0"/>
 *         &lt;element ref="{com/firstdata/Merchant/gmfV3.10}VisaSecrTxnAD" minOccurs="0"/>
 *         &lt;element ref="{com/firstdata/Merchant/gmfV3.10}CAVVResultCode" minOccurs="0"/>
 *         &lt;element ref="{com/firstdata/Merchant/gmfV3.10}AmexXID" minOccurs="0"/>
 *         &lt;element ref="{com/firstdata/Merchant/gmfV3.10}AmexSecrAD" minOccurs="0"/>
 *         &lt;element ref="{com/firstdata/Merchant/gmfV3.10}Safekey" minOccurs="0"/>
 *         &lt;element ref="{com/firstdata/Merchant/gmfV3.10}UCAFCollectInd" minOccurs="0"/>
 *         &lt;element ref="{com/firstdata/Merchant/gmfV3.10}MCSecrAD" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SecrTxnGrp", propOrder = {
    "visaXID",
    "visaSecrTxnAD",
    "cavvResultCode",
    "amexXID",
    "amexSecrAD",
    "safekey",
    "ucafCollectInd",
    "mcSecrAD"
})
public class SecrTxnGrp {

    @XmlElement(name = "VisaXID")
    protected String visaXID;
    @XmlElement(name = "VisaSecrTxnAD")
    protected String visaSecrTxnAD;
    @XmlElement(name = "CAVVResultCode")
    protected String cavvResultCode;
    @XmlElement(name = "AmexXID")
    protected String amexXID;
    @XmlElement(name = "AmexSecrAD")
    protected String amexSecrAD;
    @XmlElement(name = "Safekey")
    protected String safekey;
    @XmlElement(name = "UCAFCollectInd")
    protected String ucafCollectInd;
    @XmlElement(name = "MCSecrAD")
    protected String mcSecrAD;

    /**
     * Gets the value of the visaXID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVisaXID() {
        return visaXID;
    }

    /**
     * Sets the value of the visaXID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVisaXID(String value) {
        this.visaXID = value;
    }

    /**
     * Gets the value of the visaSecrTxnAD property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVisaSecrTxnAD() {
        return visaSecrTxnAD;
    }

    /**
     * Sets the value of the visaSecrTxnAD property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVisaSecrTxnAD(String value) {
        this.visaSecrTxnAD = value;
    }

    /**
     * Gets the value of the cavvResultCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCAVVResultCode() {
        return cavvResultCode;
    }

    /**
     * Sets the value of the cavvResultCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCAVVResultCode(String value) {
        this.cavvResultCode = value;
    }

    /**
     * Gets the value of the amexXID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAmexXID() {
        return amexXID;
    }

    /**
     * Sets the value of the amexXID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAmexXID(String value) {
        this.amexXID = value;
    }

    /**
     * Gets the value of the amexSecrAD property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAmexSecrAD() {
        return amexSecrAD;
    }

    /**
     * Sets the value of the amexSecrAD property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAmexSecrAD(String value) {
        this.amexSecrAD = value;
    }

    /**
     * Gets the value of the safekey property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSafekey() {
        return safekey;
    }

    /**
     * Sets the value of the safekey property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSafekey(String value) {
        this.safekey = value;
    }

    /**
     * Gets the value of the ucafCollectInd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUCAFCollectInd() {
        return ucafCollectInd;
    }

    /**
     * Sets the value of the ucafCollectInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUCAFCollectInd(String value) {
        this.ucafCollectInd = value;
    }

    /**
     * Gets the value of the mcSecrAD property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMCSecrAD() {
        return mcSecrAD;
    }

    /**
     * Sets the value of the mcSecrAD property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMCSecrAD(String value) {
        this.mcSecrAD = value;
    }

}
