//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.30 at 12:18:26 PM EDT 
//


package com.rsa.transarmor.dto;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for StoredValueGrp complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="StoredValueGrp">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{com/firstdata/Merchant/gmfV3.10}EschtblTxn" minOccurs="0"/>
 *         &lt;element ref="{com/firstdata/Merchant/gmfV3.10}CardClass" minOccurs="0"/>
 *         &lt;element ref="{com/firstdata/Merchant/gmfV3.10}CardCost" minOccurs="0"/>
 *         &lt;element ref="{com/firstdata/Merchant/gmfV3.10}FACode" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "StoredValueGrp", propOrder = {
    "eschtblTxn",
    "cardClass",
    "cardCost",
    "faCode"
})
public class StoredValueGrp {

    @XmlElement(name = "EschtblTxn")
    protected EschtblTxnType eschtblTxn;
    @XmlElement(name = "CardClass")
    protected String cardClass;
    @XmlElement(name = "CardCost")
    protected String cardCost;
    @XmlElement(name = "FACode")
    protected String faCode;

    /**
     * Gets the value of the eschtblTxn property.
     * 
     * @return
     *     possible object is
     *     {@link EschtblTxnType }
     *     
     */
    public EschtblTxnType getEschtblTxn() {
        return eschtblTxn;
    }

    /**
     * Sets the value of the eschtblTxn property.
     * 
     * @param value
     *     allowed object is
     *     {@link EschtblTxnType }
     *     
     */
    public void setEschtblTxn(EschtblTxnType value) {
        this.eschtblTxn = value;
    }

    /**
     * Gets the value of the cardClass property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCardClass() {
        return cardClass;
    }

    /**
     * Sets the value of the cardClass property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCardClass(String value) {
        this.cardClass = value;
    }

    /**
     * Gets the value of the cardCost property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCardCost() {
        return cardCost;
    }

    /**
     * Sets the value of the cardCost property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCardCost(String value) {
        this.cardCost = value;
    }

    /**
     * Gets the value of the faCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFACode() {
        return faCode;
    }

    /**
     * Sets the value of the faCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFACode(String value) {
        this.faCode = value;
    }

}
