//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.30 at 12:18:26 PM EDT 
//


package com.rsa.transarmor.dto;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TAGrp complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TAGrp">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{com/firstdata/Merchant/gmfV3.10}SctyLvl" minOccurs="0"/>
 *         &lt;element ref="{com/firstdata/Merchant/gmfV3.10}EncrptType" minOccurs="0"/>
 *         &lt;element ref="{com/firstdata/Merchant/gmfV3.10}EncrptTrgt" minOccurs="0"/>
 *         &lt;element ref="{com/firstdata/Merchant/gmfV3.10}KeyID" minOccurs="0"/>
 *         &lt;element ref="{com/firstdata/Merchant/gmfV3.10}EncrptBlock" minOccurs="0"/>
 *         &lt;element ref="{com/firstdata/Merchant/gmfV3.10}TknType" minOccurs="0"/>
 *         &lt;element ref="{com/firstdata/Merchant/gmfV3.10}Tkn" minOccurs="0"/>
 *         &lt;element ref="{com/firstdata/Merchant/gmfV3.10}SctyKeyUpdInd" minOccurs="0"/>
 *         &lt;element ref="{com/firstdata/Merchant/gmfV3.10}TASctyKey" minOccurs="0"/>
 *         &lt;element ref="{com/firstdata/Merchant/gmfV3.10}TAExpDate" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TAGrp", propOrder = {
    "sctyLvl",
    "encrptType",
    "encrptTrgt",
    "keyID",
    "encrptBlock",
    "tknType",
    "tkn",
    "sctyKeyUpdInd",
    "taSctyKey",
    "taExpDate"
})
public class TAGrp {

    @XmlElement(name = "SctyLvl")
    protected SctyLvlType sctyLvl;
    @XmlElement(name = "EncrptType")
    protected EncrptTypeType encrptType;
    @XmlElement(name = "EncrptTrgt")
    protected EncrptTrgtType encrptTrgt;
    @XmlElement(name = "KeyID")
    protected String keyID;
    @XmlElement(name = "EncrptBlock")
    protected String encrptBlock;
    @XmlElement(name = "TknType")
    protected String tknType;
    @XmlElement(name = "Tkn")
    protected String tkn;
    @XmlElement(name = "SctyKeyUpdInd")
    protected String sctyKeyUpdInd;
    @XmlElement(name = "TASctyKey")
    protected String taSctyKey;
    @XmlElement(name = "TAExpDate")
    protected String taExpDate;

    /**
     * Gets the value of the sctyLvl property.
     * 
     * @return
     *     possible object is
     *     {@link SctyLvlType }
     *     
     */
    public SctyLvlType getSctyLvl() {
        return sctyLvl;
    }

    /**
     * Sets the value of the sctyLvl property.
     * 
     * @param value
     *     allowed object is
     *     {@link SctyLvlType }
     *     
     */
    public void setSctyLvl(SctyLvlType value) {
        this.sctyLvl = value;
    }

    /**
     * Gets the value of the encrptType property.
     * 
     * @return
     *     possible object is
     *     {@link EncrptTypeType }
     *     
     */
    public EncrptTypeType getEncrptType() {
        return encrptType;
    }

    /**
     * Sets the value of the encrptType property.
     * 
     * @param value
     *     allowed object is
     *     {@link EncrptTypeType }
     *     
     */
    public void setEncrptType(EncrptTypeType value) {
        this.encrptType = value;
    }

    /**
     * Gets the value of the encrptTrgt property.
     * 
     * @return
     *     possible object is
     *     {@link EncrptTrgtType }
     *     
     */
    public EncrptTrgtType getEncrptTrgt() {
        return encrptTrgt;
    }

    /**
     * Sets the value of the encrptTrgt property.
     * 
     * @param value
     *     allowed object is
     *     {@link EncrptTrgtType }
     *     
     */
    public void setEncrptTrgt(EncrptTrgtType value) {
        this.encrptTrgt = value;
    }

    /**
     * Gets the value of the keyID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKeyID() {
        return keyID;
    }

    /**
     * Sets the value of the keyID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKeyID(String value) {
        this.keyID = value;
    }

    /**
     * Gets the value of the encrptBlock property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEncrptBlock() {
        return encrptBlock;
    }

    /**
     * Sets the value of the encrptBlock property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEncrptBlock(String value) {
        this.encrptBlock = value;
    }

    /**
     * Gets the value of the tknType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTknType() {
        return tknType;
    }

    /**
     * Sets the value of the tknType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTknType(String value) {
        this.tknType = value;
    }

    /**
     * Gets the value of the tkn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTkn() {
        return tkn;
    }

    /**
     * Sets the value of the tkn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTkn(String value) {
        this.tkn = value;
    }

    /**
     * Gets the value of the sctyKeyUpdInd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSctyKeyUpdInd() {
        return sctyKeyUpdInd;
    }

    /**
     * Sets the value of the sctyKeyUpdInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSctyKeyUpdInd(String value) {
        this.sctyKeyUpdInd = value;
    }

    /**
     * Gets the value of the taSctyKey property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTASctyKey() {
        return taSctyKey;
    }

    /**
     * Sets the value of the taSctyKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTASctyKey(String value) {
        this.taSctyKey = value;
    }

    /**
     * Gets the value of the taExpDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTAExpDate() {
        return taExpDate;
    }

    /**
     * Sets the value of the taExpDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTAExpDate(String value) {
        this.taExpDate = value;
    }

}
