//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.30 at 12:18:26 PM EDT 
//


package com.rsa.transarmor.dto;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for VoidTOReversalRequestDetails complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="VoidTOReversalRequestDetails">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="CommonGrp" type="{com/firstdata/Merchant/gmfV3.10}CommonGrp" minOccurs="0"/>
 *         &lt;element name="BillPayGrp" type="{com/firstdata/Merchant/gmfV3.10}BillPayGrp" minOccurs="0"/>
 *         &lt;element name="AltMerchNameAndAddrGrp" type="{com/firstdata/Merchant/gmfV3.10}AltMerchNameAndAddrGrp" minOccurs="0"/>
 *         &lt;element name="CardGrp" type="{com/firstdata/Merchant/gmfV3.10}CardGrp" minOccurs="0"/>
 *         &lt;element name="CheckGrp" type="{com/firstdata/Merchant/gmfV3.10}CheckGrp" minOccurs="0"/>
 *         &lt;element name="TeleCheckECAGrp" type="{com/firstdata/Merchant/gmfV3.10}TeleCheckECAGrp" minOccurs="0"/>
 *         &lt;element name="PINGrp" type="{com/firstdata/Merchant/gmfV3.10}PINGrp" minOccurs="0"/>
 *         &lt;element name="AddtlAmtGrp" type="{com/firstdata/Merchant/gmfV3.10}AddtlAmtGrp" maxOccurs="6" minOccurs="0"/>
 *         &lt;element name="EMVGrp" type="{com/firstdata/Merchant/gmfV3.10}EMVGrp" minOccurs="0"/>
 *         &lt;element name="TAGrp" type="{com/firstdata/Merchant/gmfV3.10}TAGrp" minOccurs="0"/>
 *         &lt;element name="OfferGrp" type="{com/firstdata/Merchant/gmfV3.10}OfferGrp" minOccurs="0"/>
 *         &lt;element name="EcommGrp" type="{com/firstdata/Merchant/gmfV3.10}EcommGrp" minOccurs="0"/>
 *         &lt;element name="SecrTxnGrp" type="{com/firstdata/Merchant/gmfV3.10}SecrTxnGrp" minOccurs="0"/>
 *         &lt;choice>
 *           &lt;element name="VisaGrp" type="{com/firstdata/Merchant/gmfV3.10}VisaGrp" minOccurs="0"/>
 *           &lt;element name="MCGrp" type="{com/firstdata/Merchant/gmfV3.10}MCGrp" minOccurs="0"/>
 *           &lt;element name="DSGrp" type="{com/firstdata/Merchant/gmfV3.10}DSGrp" minOccurs="0"/>
 *           &lt;element name="AmexGrp" type="{com/firstdata/Merchant/gmfV3.10}AmexGrp" minOccurs="0"/>
 *         &lt;/choice>
 *         &lt;element name="EbtGrp" type="{com/firstdata/Merchant/gmfV3.10}EbtGrp" minOccurs="0"/>
 *         &lt;element name="EWICDetGrp" type="{com/firstdata/Merchant/gmfV3.10}EWICDetGrp" maxOccurs="50" minOccurs="0"/>
 *         &lt;element name="DebitGrp" type="{com/firstdata/Merchant/gmfV3.10}DebitGrp" minOccurs="0"/>
 *         &lt;element name="PurchCardlvl2Grp" type="{com/firstdata/Merchant/gmfV3.10}PurchCardlvl2Grp" minOccurs="0"/>
 *         &lt;element name="PurchCardlvl3Grp" type="{com/firstdata/Merchant/gmfV3.10}PurchCardlvl3Grp" maxOccurs="999" minOccurs="0"/>
 *         &lt;element name="CustInfoGrp" type="{com/firstdata/Merchant/gmfV3.10}CustInfoGrp" minOccurs="0"/>
 *         &lt;element name="OrderGrp" type="{com/firstdata/Merchant/gmfV3.10}OrderGrp" minOccurs="0"/>
 *         &lt;element name="StoredValueGrp" type="{com/firstdata/Merchant/gmfV3.10}StoredValueGrp" minOccurs="0"/>
 *         &lt;element name="OrigAuthGrp" type="{com/firstdata/Merchant/gmfV3.10}OrigAuthGrp" minOccurs="0"/>
 *         &lt;element name="DCCGrp" type="{com/firstdata/Merchant/gmfV3.10}DCCGrp" minOccurs="0"/>
 *         &lt;element name="ProdCodeGrp" type="{com/firstdata/Merchant/gmfV3.10}ProdCodeGrp" minOccurs="0"/>
 *         &lt;element name="ProdCodeDetGrp" type="{com/firstdata/Merchant/gmfV3.10}ProdCodeDetGrp" maxOccurs="10" minOccurs="0"/>
 *         &lt;element name="FltGrp" type="{com/firstdata/Merchant/gmfV3.10}FltGrp" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "VoidTOReversalRequestDetails", propOrder = {
    "commonGrp",
    "billPayGrp",
    "altMerchNameAndAddrGrp",
    "cardGrp",
    "checkGrp",
    "teleCheckECAGrp",
    "pinGrp",
    "addtlAmtGrp",
    "emvGrp",
    "taGrp",
    "offerGrp",
    "ecommGrp",
    "secrTxnGrp",
    "visaGrp",
    "mcGrp",
    "dsGrp",
    "amexGrp",
    "ebtGrp",
    "ewicDetGrp",
    "debitGrp",
    "purchCardlvl2Grp",
    "purchCardlvl3Grp",
    "custInfoGrp",
    "orderGrp",
    "storedValueGrp",
    "origAuthGrp",
    "dccGrp",
    "prodCodeGrp",
    "prodCodeDetGrp",
    "fltGrp"
})
public class VoidTOReversalRequestDetails {

    @XmlElement(name = "CommonGrp")
    protected CommonGrp commonGrp;
    @XmlElement(name = "BillPayGrp")
    protected BillPayGrp billPayGrp;
    @XmlElement(name = "AltMerchNameAndAddrGrp")
    protected AltMerchNameAndAddrGrp altMerchNameAndAddrGrp;
    @XmlElement(name = "CardGrp")
    protected CardGrp cardGrp;
    @XmlElement(name = "CheckGrp")
    protected CheckGrp checkGrp;
    @XmlElement(name = "TeleCheckECAGrp")
    protected TeleCheckECAGrp teleCheckECAGrp;
    @XmlElement(name = "PINGrp")
    protected PINGrp pinGrp;
    @XmlElement(name = "AddtlAmtGrp")
    protected List<AddtlAmtGrp> addtlAmtGrp;
    @XmlElement(name = "EMVGrp")
    protected EMVGrp emvGrp;
    @XmlElement(name = "TAGrp")
    protected TAGrp taGrp;
    @XmlElement(name = "OfferGrp")
    protected OfferGrp offerGrp;
    @XmlElement(name = "EcommGrp")
    protected EcommGrp ecommGrp;
    @XmlElement(name = "SecrTxnGrp")
    protected SecrTxnGrp secrTxnGrp;
    @XmlElement(name = "VisaGrp")
    protected VisaGrp visaGrp;
    @XmlElement(name = "MCGrp")
    protected MCGrp mcGrp;
    @XmlElement(name = "DSGrp")
    protected DSGrp dsGrp;
    @XmlElement(name = "AmexGrp")
    protected AmexGrp amexGrp;
    @XmlElement(name = "EbtGrp")
    protected EbtGrp ebtGrp;
    @XmlElement(name = "EWICDetGrp")
    protected List<EWICDetGrp> ewicDetGrp;
    @XmlElement(name = "DebitGrp")
    protected DebitGrp debitGrp;
    @XmlElement(name = "PurchCardlvl2Grp")
    protected PurchCardlvl2Grp purchCardlvl2Grp;
    @XmlElement(name = "PurchCardlvl3Grp")
    protected List<PurchCardlvl3Grp> purchCardlvl3Grp;
    @XmlElement(name = "CustInfoGrp")
    protected CustInfoGrp custInfoGrp;
    @XmlElement(name = "OrderGrp")
    protected OrderGrp orderGrp;
    @XmlElement(name = "StoredValueGrp")
    protected StoredValueGrp storedValueGrp;
    @XmlElement(name = "OrigAuthGrp")
    protected OrigAuthGrp origAuthGrp;
    @XmlElement(name = "DCCGrp")
    protected DCCGrp dccGrp;
    @XmlElement(name = "ProdCodeGrp")
    protected ProdCodeGrp prodCodeGrp;
    @XmlElement(name = "ProdCodeDetGrp")
    protected List<ProdCodeDetGrp> prodCodeDetGrp;
    @XmlElement(name = "FltGrp")
    protected FltGrp fltGrp;

    /**
     * Gets the value of the commonGrp property.
     * 
     * @return
     *     possible object is
     *     {@link CommonGrp }
     *     
     */
    public CommonGrp getCommonGrp() {
        return commonGrp;
    }

    /**
     * Sets the value of the commonGrp property.
     * 
     * @param value
     *     allowed object is
     *     {@link CommonGrp }
     *     
     */
    public void setCommonGrp(CommonGrp value) {
        this.commonGrp = value;
    }

    /**
     * Gets the value of the billPayGrp property.
     * 
     * @return
     *     possible object is
     *     {@link BillPayGrp }
     *     
     */
    public BillPayGrp getBillPayGrp() {
        return billPayGrp;
    }

    /**
     * Sets the value of the billPayGrp property.
     * 
     * @param value
     *     allowed object is
     *     {@link BillPayGrp }
     *     
     */
    public void setBillPayGrp(BillPayGrp value) {
        this.billPayGrp = value;
    }

    /**
     * Gets the value of the altMerchNameAndAddrGrp property.
     * 
     * @return
     *     possible object is
     *     {@link AltMerchNameAndAddrGrp }
     *     
     */
    public AltMerchNameAndAddrGrp getAltMerchNameAndAddrGrp() {
        return altMerchNameAndAddrGrp;
    }

    /**
     * Sets the value of the altMerchNameAndAddrGrp property.
     * 
     * @param value
     *     allowed object is
     *     {@link AltMerchNameAndAddrGrp }
     *     
     */
    public void setAltMerchNameAndAddrGrp(AltMerchNameAndAddrGrp value) {
        this.altMerchNameAndAddrGrp = value;
    }

    /**
     * Gets the value of the cardGrp property.
     * 
     * @return
     *     possible object is
     *     {@link CardGrp }
     *     
     */
    public CardGrp getCardGrp() {
        return cardGrp;
    }

    /**
     * Sets the value of the cardGrp property.
     * 
     * @param value
     *     allowed object is
     *     {@link CardGrp }
     *     
     */
    public void setCardGrp(CardGrp value) {
        this.cardGrp = value;
    }

    /**
     * Gets the value of the checkGrp property.
     * 
     * @return
     *     possible object is
     *     {@link CheckGrp }
     *     
     */
    public CheckGrp getCheckGrp() {
        return checkGrp;
    }

    /**
     * Sets the value of the checkGrp property.
     * 
     * @param value
     *     allowed object is
     *     {@link CheckGrp }
     *     
     */
    public void setCheckGrp(CheckGrp value) {
        this.checkGrp = value;
    }

    /**
     * Gets the value of the teleCheckECAGrp property.
     * 
     * @return
     *     possible object is
     *     {@link TeleCheckECAGrp }
     *     
     */
    public TeleCheckECAGrp getTeleCheckECAGrp() {
        return teleCheckECAGrp;
    }

    /**
     * Sets the value of the teleCheckECAGrp property.
     * 
     * @param value
     *     allowed object is
     *     {@link TeleCheckECAGrp }
     *     
     */
    public void setTeleCheckECAGrp(TeleCheckECAGrp value) {
        this.teleCheckECAGrp = value;
    }

    /**
     * Gets the value of the pinGrp property.
     * 
     * @return
     *     possible object is
     *     {@link PINGrp }
     *     
     */
    public PINGrp getPINGrp() {
        return pinGrp;
    }

    /**
     * Sets the value of the pinGrp property.
     * 
     * @param value
     *     allowed object is
     *     {@link PINGrp }
     *     
     */
    public void setPINGrp(PINGrp value) {
        this.pinGrp = value;
    }

    /**
     * Gets the value of the addtlAmtGrp property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the addtlAmtGrp property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAddtlAmtGrp().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AddtlAmtGrp }
     * 
     * 
     */
    public List<AddtlAmtGrp> getAddtlAmtGrp() {
        if (addtlAmtGrp == null) {
            addtlAmtGrp = new ArrayList<AddtlAmtGrp>();
        }
        return this.addtlAmtGrp;
    }

    /**
     * Gets the value of the emvGrp property.
     * 
     * @return
     *     possible object is
     *     {@link EMVGrp }
     *     
     */
    public EMVGrp getEMVGrp() {
        return emvGrp;
    }

    /**
     * Sets the value of the emvGrp property.
     * 
     * @param value
     *     allowed object is
     *     {@link EMVGrp }
     *     
     */
    public void setEMVGrp(EMVGrp value) {
        this.emvGrp = value;
    }

    /**
     * Gets the value of the taGrp property.
     * 
     * @return
     *     possible object is
     *     {@link TAGrp }
     *     
     */
    public TAGrp getTAGrp() {
        return taGrp;
    }

    /**
     * Sets the value of the taGrp property.
     * 
     * @param value
     *     allowed object is
     *     {@link TAGrp }
     *     
     */
    public void setTAGrp(TAGrp value) {
        this.taGrp = value;
    }

    /**
     * Gets the value of the offerGrp property.
     * 
     * @return
     *     possible object is
     *     {@link OfferGrp }
     *     
     */
    public OfferGrp getOfferGrp() {
        return offerGrp;
    }

    /**
     * Sets the value of the offerGrp property.
     * 
     * @param value
     *     allowed object is
     *     {@link OfferGrp }
     *     
     */
    public void setOfferGrp(OfferGrp value) {
        this.offerGrp = value;
    }

    /**
     * Gets the value of the ecommGrp property.
     * 
     * @return
     *     possible object is
     *     {@link EcommGrp }
     *     
     */
    public EcommGrp getEcommGrp() {
        return ecommGrp;
    }

    /**
     * Sets the value of the ecommGrp property.
     * 
     * @param value
     *     allowed object is
     *     {@link EcommGrp }
     *     
     */
    public void setEcommGrp(EcommGrp value) {
        this.ecommGrp = value;
    }

    /**
     * Gets the value of the secrTxnGrp property.
     * 
     * @return
     *     possible object is
     *     {@link SecrTxnGrp }
     *     
     */
    public SecrTxnGrp getSecrTxnGrp() {
        return secrTxnGrp;
    }

    /**
     * Sets the value of the secrTxnGrp property.
     * 
     * @param value
     *     allowed object is
     *     {@link SecrTxnGrp }
     *     
     */
    public void setSecrTxnGrp(SecrTxnGrp value) {
        this.secrTxnGrp = value;
    }

    /**
     * Gets the value of the visaGrp property.
     * 
     * @return
     *     possible object is
     *     {@link VisaGrp }
     *     
     */
    public VisaGrp getVisaGrp() {
        return visaGrp;
    }

    /**
     * Sets the value of the visaGrp property.
     * 
     * @param value
     *     allowed object is
     *     {@link VisaGrp }
     *     
     */
    public void setVisaGrp(VisaGrp value) {
        this.visaGrp = value;
    }

    /**
     * Gets the value of the mcGrp property.
     * 
     * @return
     *     possible object is
     *     {@link MCGrp }
     *     
     */
    public MCGrp getMCGrp() {
        return mcGrp;
    }

    /**
     * Sets the value of the mcGrp property.
     * 
     * @param value
     *     allowed object is
     *     {@link MCGrp }
     *     
     */
    public void setMCGrp(MCGrp value) {
        this.mcGrp = value;
    }

    /**
     * Gets the value of the dsGrp property.
     * 
     * @return
     *     possible object is
     *     {@link DSGrp }
     *     
     */
    public DSGrp getDSGrp() {
        return dsGrp;
    }

    /**
     * Sets the value of the dsGrp property.
     * 
     * @param value
     *     allowed object is
     *     {@link DSGrp }
     *     
     */
    public void setDSGrp(DSGrp value) {
        this.dsGrp = value;
    }

    /**
     * Gets the value of the amexGrp property.
     * 
     * @return
     *     possible object is
     *     {@link AmexGrp }
     *     
     */
    public AmexGrp getAmexGrp() {
        return amexGrp;
    }

    /**
     * Sets the value of the amexGrp property.
     * 
     * @param value
     *     allowed object is
     *     {@link AmexGrp }
     *     
     */
    public void setAmexGrp(AmexGrp value) {
        this.amexGrp = value;
    }

    /**
     * Gets the value of the ebtGrp property.
     * 
     * @return
     *     possible object is
     *     {@link EbtGrp }
     *     
     */
    public EbtGrp getEbtGrp() {
        return ebtGrp;
    }

    /**
     * Sets the value of the ebtGrp property.
     * 
     * @param value
     *     allowed object is
     *     {@link EbtGrp }
     *     
     */
    public void setEbtGrp(EbtGrp value) {
        this.ebtGrp = value;
    }

    /**
     * Gets the value of the ewicDetGrp property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the ewicDetGrp property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEWICDetGrp().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EWICDetGrp }
     * 
     * 
     */
    public List<EWICDetGrp> getEWICDetGrp() {
        if (ewicDetGrp == null) {
            ewicDetGrp = new ArrayList<EWICDetGrp>();
        }
        return this.ewicDetGrp;
    }

    /**
     * Gets the value of the debitGrp property.
     * 
     * @return
     *     possible object is
     *     {@link DebitGrp }
     *     
     */
    public DebitGrp getDebitGrp() {
        return debitGrp;
    }

    /**
     * Sets the value of the debitGrp property.
     * 
     * @param value
     *     allowed object is
     *     {@link DebitGrp }
     *     
     */
    public void setDebitGrp(DebitGrp value) {
        this.debitGrp = value;
    }

    /**
     * Gets the value of the purchCardlvl2Grp property.
     * 
     * @return
     *     possible object is
     *     {@link PurchCardlvl2Grp }
     *     
     */
    public PurchCardlvl2Grp getPurchCardlvl2Grp() {
        return purchCardlvl2Grp;
    }

    /**
     * Sets the value of the purchCardlvl2Grp property.
     * 
     * @param value
     *     allowed object is
     *     {@link PurchCardlvl2Grp }
     *     
     */
    public void setPurchCardlvl2Grp(PurchCardlvl2Grp value) {
        this.purchCardlvl2Grp = value;
    }

    /**
     * Gets the value of the purchCardlvl3Grp property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the purchCardlvl3Grp property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPurchCardlvl3Grp().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PurchCardlvl3Grp }
     * 
     * 
     */
    public List<PurchCardlvl3Grp> getPurchCardlvl3Grp() {
        if (purchCardlvl3Grp == null) {
            purchCardlvl3Grp = new ArrayList<PurchCardlvl3Grp>();
        }
        return this.purchCardlvl3Grp;
    }

    /**
     * Gets the value of the custInfoGrp property.
     * 
     * @return
     *     possible object is
     *     {@link CustInfoGrp }
     *     
     */
    public CustInfoGrp getCustInfoGrp() {
        return custInfoGrp;
    }

    /**
     * Sets the value of the custInfoGrp property.
     * 
     * @param value
     *     allowed object is
     *     {@link CustInfoGrp }
     *     
     */
    public void setCustInfoGrp(CustInfoGrp value) {
        this.custInfoGrp = value;
    }

    /**
     * Gets the value of the orderGrp property.
     * 
     * @return
     *     possible object is
     *     {@link OrderGrp }
     *     
     */
    public OrderGrp getOrderGrp() {
        return orderGrp;
    }

    /**
     * Sets the value of the orderGrp property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrderGrp }
     *     
     */
    public void setOrderGrp(OrderGrp value) {
        this.orderGrp = value;
    }

    /**
     * Gets the value of the storedValueGrp property.
     * 
     * @return
     *     possible object is
     *     {@link StoredValueGrp }
     *     
     */
    public StoredValueGrp getStoredValueGrp() {
        return storedValueGrp;
    }

    /**
     * Sets the value of the storedValueGrp property.
     * 
     * @param value
     *     allowed object is
     *     {@link StoredValueGrp }
     *     
     */
    public void setStoredValueGrp(StoredValueGrp value) {
        this.storedValueGrp = value;
    }

    /**
     * Gets the value of the origAuthGrp property.
     * 
     * @return
     *     possible object is
     *     {@link OrigAuthGrp }
     *     
     */
    public OrigAuthGrp getOrigAuthGrp() {
        return origAuthGrp;
    }

    /**
     * Sets the value of the origAuthGrp property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrigAuthGrp }
     *     
     */
    public void setOrigAuthGrp(OrigAuthGrp value) {
        this.origAuthGrp = value;
    }

    /**
     * Gets the value of the dccGrp property.
     * 
     * @return
     *     possible object is
     *     {@link DCCGrp }
     *     
     */
    public DCCGrp getDCCGrp() {
        return dccGrp;
    }

    /**
     * Sets the value of the dccGrp property.
     * 
     * @param value
     *     allowed object is
     *     {@link DCCGrp }
     *     
     */
    public void setDCCGrp(DCCGrp value) {
        this.dccGrp = value;
    }

    /**
     * Gets the value of the prodCodeGrp property.
     * 
     * @return
     *     possible object is
     *     {@link ProdCodeGrp }
     *     
     */
    public ProdCodeGrp getProdCodeGrp() {
        return prodCodeGrp;
    }

    /**
     * Sets the value of the prodCodeGrp property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProdCodeGrp }
     *     
     */
    public void setProdCodeGrp(ProdCodeGrp value) {
        this.prodCodeGrp = value;
    }

    /**
     * Gets the value of the prodCodeDetGrp property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the prodCodeDetGrp property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getProdCodeDetGrp().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ProdCodeDetGrp }
     * 
     * 
     */
    public List<ProdCodeDetGrp> getProdCodeDetGrp() {
        if (prodCodeDetGrp == null) {
            prodCodeDetGrp = new ArrayList<ProdCodeDetGrp>();
        }
        return this.prodCodeDetGrp;
    }

    /**
     * Gets the value of the fltGrp property.
     * 
     * @return
     *     possible object is
     *     {@link FltGrp }
     *     
     */
    public FltGrp getFltGrp() {
        return fltGrp;
    }

    /**
     * Sets the value of the fltGrp property.
     * 
     * @param value
     *     allowed object is
     *     {@link FltGrp }
     *     
     */
    public void setFltGrp(FltGrp value) {
        this.fltGrp = value;
    }

}
